"""allure-pytest 的最小型別 stub，解決 pyright strict mode 下的型別錯誤。"""

from collections.abc import Callable
from typing import Any, TypeVar

_F = TypeVar('_F', bound=Callable[..., Any])

def feature(*features: str) -> Callable[[_F], _F]: ...
def story(*stories: str) -> Callable[[_F], _F]: ...
def title(test_title: str) -> Callable[[_F], _F]: ...
def severity(severity_level: Any) -> Callable[[_F], _F]: ...
def description(test_description: str) -> Callable[[_F], _F]: ...
def link(url: str, link_type: str = ..., name: str = ...) -> Callable[[_F], _F]: ...
def issue(url: str, name: str = ...) -> Callable[[_F], _F]: ...
def step(title: str) -> Any: ...
def attach(
    body: Any, name: str = ..., attachment_type: Any = ..., extension: str = ...
) -> None: ...
